-- MySQL Script generated by MySQL Workbench
-- Mon Mar  8 02:47:34 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema stud_v21_knudsen
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema stud_v21_knudsen
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `stud_v21_knudsen` DEFAULT CHARACTER SET utf8 ;
USE `stud_v21_knudsen` ;

-- -----------------------------------------------------
-- Table `stud_v21_knudsen`.`Fakturaadresse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stud_v21_knudsen`.`Fakturaadresse` (
  `AID` INT NOT NULL AUTO_INCREMENT,
  `postnr` INT NOT NULL,
  `poststed` VARCHAR(45) NULL,
  `adresse` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`AID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stud_v21_knudsen`.`Leveringsadresse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stud_v21_knudsen`.`Leveringsadresse` (
  `AID` INT NOT NULL AUTO_INCREMENT,
  `postnr` INT NOT NULL,
  `poststed` VARCHAR(45) NULL,
  `adresse` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`AID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stud_v21_knudsen`.`Kunde`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stud_v21_knudsen`.`Kunde` (
  `KundeNr` INT NOT NULL AUTO_INCREMENT,
  `Type` VARCHAR(7) NOT NULL,
  `Epost` VARCHAR(320) NOT NULL,
  `Navn` VARCHAR(45) NOT NULL,
  `Fakturaadresse_AID` INT NULL,
  `Leveringsadresse_AID` INT NULL,
  PRIMARY KEY (`KundeNr`),
  INDEX `fk_Kunde_Fakturaadresse1_idx` (`Fakturaadresse_AID` ASC) VISIBLE,
  INDEX `fk_Kunde_Leveringsadresse1_idx` (`Leveringsadresse_AID` ASC) VISIBLE,
  CONSTRAINT `fk_Kunde_Fakturaadresse1`
    FOREIGN KEY (`Fakturaadresse_AID`)
    REFERENCES `stud_v21_knudsen`.`Fakturaadresse` (`AID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Kunde_Leveringsadresse1`
    FOREIGN KEY (`Leveringsadresse_AID`)
    REFERENCES `stud_v21_knudsen`.`Leveringsadresse` (`AID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stud_v21_knudsen`.`Telefonnummer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stud_v21_knudsen`.`Telefonnummer` (
  `Telefonnummer` INT NOT NULL,
  `Kunde_KundeNr` INT NOT NULL,
  PRIMARY KEY (`Telefonnummer`),
  INDEX `fk_Telefonnummer_Kunde_idx` (`Kunde_KundeNr` ASC) VISIBLE,
  CONSTRAINT `fk_Telefonnummer_Kunde`
    FOREIGN KEY (`Kunde_KundeNr`)
    REFERENCES `stud_v21_knudsen`.`Kunde` (`KundeNr`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stud_v21_knudsen`.`Leveringsadresse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stud_v21_knudsen`.`Leveringsadresse` (
  `AID` INT NOT NULL AUTO_INCREMENT,
  `postnr` INT NOT NULL,
  `poststed` VARCHAR(45) NULL,
  `adresse` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`AID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stud_v21_knudsen`.`Kundebehandler`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stud_v21_knudsen`.`Kundebehandler` (
  `KBID` INT NOT NULL AUTO_INCREMENT,
  `Fornavn` VARCHAR(45) NOT NULL,
  `Etternavn` VARCHAR(45) NOT NULL,
  `Telefonnummer` INT NOT NULL,
  PRIMARY KEY (`KBID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stud_v21_knudsen`.`UtstyrsDetaljer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stud_v21_knudsen`.`UtstyrsDetaljer` (
  `UtstyrsID` INT NOT NULL,
  `Utstyrstype` VARCHAR(45) NOT NULL,
  `Utstyrsmerke` VARCHAR(45) NOT NULL,
  `Utstyrsmodell` VARCHAR(45) NOT NULL,
  `Antall` INT NOT NULL,
  `LeieprisDøgn` DOUBLE(8,2) NOT NULL,
  `UtstyrsKategori` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`UtstyrsID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stud_v21_knudsen`.`Utstyr`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stud_v21_knudsen`.`Utstyr` (
  `InstansID` INT NOT NULL,
  `SistVedlikeholdt` DATE NULL,
  `NesteVedlikehold` DATE NULL,
  `UtstyrsDetaljer_UtstyrsID` INT NOT NULL,
  PRIMARY KEY (`InstansID`, `UtstyrsDetaljer_UtstyrsID`),
  INDEX `fk_Utstyr_UtstyrsDetaljer1_idx` (`UtstyrsDetaljer_UtstyrsID` ASC) VISIBLE,
  CONSTRAINT `fk_Utstyr_UtstyrsDetaljer1`
    FOREIGN KEY (`UtstyrsDetaljer_UtstyrsID`)
    REFERENCES `stud_v21_knudsen`.`UtstyrsDetaljer` (`UtstyrsID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stud_v21_knudsen`.`Utleie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stud_v21_knudsen`.`Utleie` (
  `UtleidDato` DATE NOT NULL,
  `InnlevertDato` DATE NULL,
  `Betalingsmåte` VARCHAR(45) NOT NULL,
  `LeveringsKostnad` VARCHAR(45) NULL,
  `Kundebehandler_KBID` INT NOT NULL,
  `Utstyr_UtstyrsID` INT NOT NULL,
  `Utstyr_InstansID` INT NOT NULL,
  `Kunde_KundeNr` INT NOT NULL,
  PRIMARY KEY (`Kundebehandler_KBID`, `Utstyr_UtstyrsID`, `Utstyr_InstansID`),
  INDEX `fk_Utleie_Utstyr1_idx` (`Utstyr_UtstyrsID` ASC, `Utstyr_InstansID` ASC) VISIBLE,
  INDEX `fk_Utleie_Kunde1_idx` (`Kunde_KundeNr` ASC) VISIBLE,
  CONSTRAINT `fk_Utleie_Kundebehandler1`
    FOREIGN KEY (`Kundebehandler_KBID`)
    REFERENCES `stud_v21_knudsen`.`Kundebehandler` (`KBID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Utleie_Utstyr1`
    FOREIGN KEY (`Utstyr_InstansID`)
    REFERENCES `stud_v21_knudsen`.`Utstyr` (`InstansID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Utleie_Kunde1`
    FOREIGN KEY (`Kunde_KundeNr`)
    REFERENCES `stud_v21_knudsen`.`Kunde` (`KundeNr`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
